### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by tpoisonooo** [bltlab/query-ner#1]
Thanks for your great job, I would like to ask 2 questions.

1. Based on my understanding, e-commerce queries are generally not very long, I wonder if this is due to **differences in language**
  
    For example query in your paper
    
    ```bash
    High- end[speaker cover] for [B & W][805d]1 pairmade of [velvet] [suede]made to order 
    ```
    
    I guess `[]` in this sentence means **optional** ?

2.  Although GPT4 does not perform well on query rewriting task, can LLMs perform well in entity word segmentation?

**Comment by cpalenmichel** [comment]
Hi, thanks for your interest in our work! 

We'd like to keep the focus of issues in the repo on issues / concerns / challenges relating to the dataset itself. Please direct future questions like these or other less directly related discussion to cpalenmichel AT brandeis DOT edu and lignos AT brandeis DOT edu. Thanks! 

1. The brackets `[]` are to show spans of tokens that are considered as an entity. Yes, e-commerce queries do often tend to be on the shorter side, but there are also cases that can end up being quite a bit longer with 4 or more tokens and we do see some similar to the length of the example about the speaker cover. Length of queries of course depends on many factors, like language (as you mentioned), but also the product category, the particular e-commerce platform being used, etc. 

2. With LLMs it always seems to depend on how they are being used. I can say in another project we tried instruction fine-tuning Llama 7b on the queryNER dataset and the performance was about the same as fine-tuning BERT. That said, it's possible a larger model or a different prompt tuning approach or something else could do better. One difficulty with LLMs for sequence labeling / token classification is that they aren't constrained to generating correctly formatted output and so sometimes will not label certain tokens or produce output that can't easily be mapped back to the input tokens.
